import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Comprehensive dictionary keyed by standard short codes
const translations = {
  en: {
    'greeting.morning': 'Good morning',
    'greeting.afternoon': 'Good afternoon',
    'greeting.evening': 'Good evening',
    'dashboard.bodyInPhase': 'Your body is in the',
    'dashboard.protectedPhase': 'protected phase',
    'river.title': 'Signal River',
    'river.tooltip': "Your body's signals over the last 7 days",
    'river.patternNoticed': 'Pattern noticed',
    'river.subtitle': "Your body's signals over the last 7 days",
    'days.fatigue': 'Fatigue',
    'days.poorSleep': 'Poor sleep',
    'days.headache': 'Headache',
    'days.mildCramps': 'Mild cramps',
    'days.ovulationWindow': 'Ovulation window',
    'days.today': 'Today',
    'days.thu': 'Thu',
    'days.fri': 'Fri',
    'days.sat': 'Sat',
    'days.sun': 'Sun',
    'days.mon': 'Mon',
    'days.tue': 'Tue',
    'dates.may9': 'May 9',
    'dates.may10': 'May 10',
    'dates.may11': 'May 11',
    'dates.may12': 'May 12',
    'dates.may13': 'May 13',
    'dates.may14': 'May 14',
    'dates.may15': 'May 15',
    'river.recentFlow': 'Your recent signal flow:',
    'river.flowDescription': 'fatigue and poor sleep appeared together twice this week. Your flow is calmer today.',
    'river.disclaimer': 'This is a personalized interpretation, not a medical diagnosis.',
    'aura.badge': 'Aura AI · Supportive Sisterhood',
    'aura.encrypted': 'Encrypted',
    'aura.safeSpaceTitle': 'Your Safe Space Guidance',
    'aura.default': 'Prioritizing rest during high-stress weeks protects your hormonal rhythm. Take 5 deep breaths today.',
    'aura.menstrual': 'Your body is in its renewal phase. Warm hydration and gentle pacing will support your comfort today.',
    'aura.luteal': 'Progesterone is shifting inward. Give yourself permission to step back and protect your emotional space.',
    'aura.crampy': 'We noticed discomfort logged. Consider a gentle stretch or reaching out to a specialist if needed.',
    'focus.title': "Today's Focus",
    'focus.logSymptoms': 'Log symptoms',
    'focus.logMood': 'Log mood',
    'focus.logBBT': 'Log BBT',
    'focus.logMedication': 'Log medication',
    'upcoming.title': 'Upcoming',
    'upcoming.nextPeriod': 'Next Period Expected',
    'upcoming.inDays': 'In',
    'upcoming.daysText': 'days',
    'upcoming.activeNow': 'Active now',
    'upcoming.onTrack': 'On track',
    'upcoming.checkup': 'Wellness Checkup',
    'upcoming.scheduled': 'Scheduled via Screening Hub',
    'actions.edit': 'Edit',
    'actions.viewAll': 'View all'
  },
  ar: {
    'greeting.morning': 'صباح الخير',
    'greeting.afternoon': 'مساء الخير',
    'greeting.evening': 'مساء الخير',
    'dashboard.bodyInPhase': 'جسمك في',
    'dashboard.protectedPhase': 'المرحلة المحمية',
    'river.title': 'نهر الإشارات',
    'river.tooltip': 'إشارات جسمك خلال الأيام الـ 7 الماضية',
    'river.patternNoticed': 'تم ملاحظة نمط',
    'river.subtitle': 'إشارات جسمك خلال الأيام الـ 7 الماضية',
    'days.fatigue': 'إرهاق',
    'days.poorSleep': 'نوم سيء',
    'days.headache': 'صداع',
    'days.mildCramps': 'تقلصات خفيفة',
    'days.ovulationWindow': 'فترة الإباضة',
    'days.today': 'اليوم',
    'days.thu': 'الخميس',
    'days.fri': 'الجمعة',
    'days.sat': 'السبت',
    'days.sun': 'الأحد',
    'days.mon': 'الإثنين',
    'days.tue': 'الثلاثاء',
    'dates.may9': '٩ مايو',
    'dates.may10': '١٠ مايو',
    'dates.may11': '١١ مايو',
    'dates.may12': '١٢ مايو',
    'dates.may13': '١٣ مايو',
    'dates.may14': '١٤ مايو',
    'dates.may15': '١٥ مايو',
    'river.recentFlow': 'تدفق إشاراتك الأخير:',
    'river.flowDescription': 'ظهر الإرهاق وسوء النوم معاً مرتين هذا الأسبوع. تدفقك أهدأ اليوم.',
    'river.disclaimer': 'هذه قراءة مخصصة وليست تشخيصاً طبياً.',
    'aura.badge': 'أورا الذكاء الاصطناعي · أخوة داعمة',
    'aura.encrypted': 'مشفر',
    'aura.safeSpaceTitle': 'إرشادات مساحتك الآمنة',
    'aura.default': 'إعطاء الأولوية للراحة خلال أسابيع الضغط العالي يحمي إيقاع هرموناتك. خذي ٥ أنفاس عميقة اليوم.',
    'aura.menstrual': 'جسمك في مرحلة التجديد. السوائل الدافئة والوتيرة الهادئة ستدعم راحتك اليوم.',
    'aura.luteal': 'البروجسترون يتجه للداخل. امنحي نفسك الإذن بالتراجع وحماية مساحتك العاطفية.',
    'aura.crampy': 'لاحظنا تسجيل شعور عدم راحة. فكري في تمارين إطالة خفيفة أو التواصل مع مختص إذا لزم الأمر.',
    'focus.title': 'تركيز اليوم',
    'focus.logSymptoms': 'تسجيل الأعراض',
    'focus.logMood': 'تسجيل المزاج',
    'focus.logBBT': 'تسجيل حرارة الجسم',
    'focus.logMedication': 'تسجيل الأدوية',
    'upcoming.title': 'القادم',
    'upcoming.nextPeriod': 'الدورة القادمة المتوقعة',
    'upcoming.inDays': 'خلال',
    'upcoming.daysText': 'أيام',
    'upcoming.activeNow': 'نشطة الآن',
    'upcoming.onTrack': 'على المسار',
    'upcoming.checkup': 'فحص العافية',
    'upcoming.scheduled': 'مجدول عبر مركز الفحص',
    'actions.edit': 'تعديل',
    'actions.viewAll': 'عرض الكل'
  },
  fr: {
    'greeting.morning': 'Bonjour',
    'greeting.afternoon': 'Bon après-midi',
    'greeting.evening': 'Bonsoir',
    'dashboard.bodyInPhase': 'Votre corps est dans la',
    'dashboard.protectedPhase': 'phase protégée',
    'river.title': 'Rivière des Signaux',
    'river.tooltip': 'Les signaux de votre corps au cours des 7 derniers jours',
    'river.patternNoticed': 'Modèle détecté',
    'river.subtitle': 'Les signaux de votre corps au cours des 7 derniers jours',
    'days.fatigue': 'Fatigue',
    'days.poorSleep': 'Sommeil agité',
    'days.headache': 'Maux de tête',
    'days.mildCramps': 'Légères crampes',
    'days.ovulationWindow': "Fenêtre d'ovulation",
    'days.today': "Aujourd'hui",
    'days.thu': 'Jeu',
    'days.fri': 'Ven',
    'days.sat': 'Sam',
    'days.sun': 'Dim',
    'days.mon': 'Lun',
    'days.tue': 'Mar',
    'dates.may9': '9 mai',
    'dates.may10': '10 mai',
    'dates.may11': '11 mai',
    'dates.may12': '12 mai',
    'dates.may13': '13 mai',
    'dates.may14': '14 mai',
    'dates.may15': '15 mai',
    'river.recentFlow': 'Votre flux de signaux récent :',
    'river.flowDescription': 'la fatigue et le mauvais sommeil sont apparus ensemble deux fois cette semaine. Votre flux est plus calme aujourd’hui.',
    'river.disclaimer': "Ceci est une interprétation personnalisée, pas un diagnostic médical.",
    'aura.badge': 'Aura IA · Sororité de soutien',
    'aura.encrypted': 'Crypté',
    'aura.safeSpaceTitle': 'Conseils pour votre espace sécurisé',
    'aura.default': 'Prioriser le repos pendant les semaines de stress intense protège votre rythme hormonal. Prenez 5 respirations profondes aujourd’hui.',
    'aura.menstrual': 'Votre corps est en phase de renouvellement. Une hydratation chaude et un rythme doux soutiendront votre confort.',
    'aura.luteal': 'La progestérone évolue vers l’intérieur. Donnez-vous la permission de prendre du recul et de protéger votre espace émotionnel.',
    'aura.crampy': 'Nous avons détecté un signal d’inconfort. Envisagez des étirements doux ou consultez un spécialiste si nécessaire.',
    'focus.title': "Focus d'aujourd'hui",
    'focus.logSymptoms': 'Enregistrer les symptômes',
    'focus.logMood': "Enregistrer l'humeur",
    'focus.logBBT': 'Enregistrer la température',
    'focus.logMedication': 'Enregistrer les médicaments',
    'upcoming.title': 'À venir',
    'upcoming.nextPeriod': 'Prochaines règles prévues',
    'upcoming.inDays': 'Dans',
    'upcoming.daysText': 'jours',
    'upcoming.activeNow': 'Actif maintenant',
    'upcoming.onTrack': 'Sur la bonne voie',
    'upcoming.checkup': 'Bilan de santé',
    'upcoming.scheduled': 'Programmé via le centre de dépistage',
    'actions.edit': 'Modifier',
    'actions.viewAll': 'Voir tout'
  },
  darija: {
    'greeting.morning': 'صباح الخير',
    'greeting.afternoon': 'مساء الخير',
    'greeting.evening': 'مساء الخير',
    'dashboard.bodyInPhase': 'الجسم ديالك فالمرحلة',
    'dashboard.protectedPhase': 'المحمية',
    'river.title': 'وادي الإشارات',
    'river.tooltip': 'الإشارات ديال جسمك فالـ 7 أيام الأخيرة',
    'river.patternNoticed': 'تم ملاحظة نمط',
    'river.subtitle': 'الإشارات ديال جسمك فالـ 7 أيام الأخيرة',
    'days.fatigue': 'عياء',
    'days.poorSleep': 'نعاس ماشي هو هداك',
    'days.headache': 'وجع الرأس',
    'days.mildCramps': 'حريق خفيف',
    'days.ovulationWindow': 'فترة الإباضة',
    'days.today': 'اليوم',
    'days.thu': 'الخميس',
    'days.fri': 'الجمعة',
    'days.sat': 'السبت',
    'days.sun': 'الأحد',
    'days.mon': 'الإثنين',
    'days.tue': 'الثلاثاء',
    'dates.may9': '9 ماي',
    'dates.may10': '10 ماي',
    'dates.may11': '11 ماي',
    'dates.may12': '12 ماي',
    'dates.may13': '13 ماي',
    'dates.may14': '14 ماي',
    'dates.may15': '15 ماي',
    'river.recentFlow': 'التدفق الأخير ديال إشاراتك:',
    'river.flowDescription': 'العياء وقلة النعاس بانوا بجوج جوج مرات هاد السيمانة. التدفق هادئ اليوم.',
    'river.disclaimer': 'هادشي تفسير شخصي ماشي تشخيص طبي.',
    'aura.badge': 'أورا الذكاء الاصطناعي · مساندة النساء',
    'aura.encrypted': 'مشفر',
    'aura.safeSpaceTitle': 'إرشادات المساحة الآمنة ديالك',
    'aura.default': 'الراحة فالأسام ديال الستريس كتحمي الهرمونات ديالك. تنفسي بعمق 5 المرات اليوم.',
    'aura.menstrual': 'الجسم ديالك كيدوز من مرحلة التجديد. السوائل السخونة والراحة غادي يعاونوك اليوم.',
    'aura.luteal': 'البروجسترون كيتغير لداخل. عطي لراسك الوقت باش ترتاحي وتحمي المساحة العاطفية ديالك.',
    'aura.crampy': 'لاحظنا بلي تسجل عندك حريق. فكري ديري تمدد خفيف ولا تواصلي مع مختص يلا كان ضروري.',
    'focus.title': 'تركيز اليوم',
    'focus.logSymptoms': 'سجل الأعراض',
    'focus.logMood': 'سجل الحالة النفسية',
    'focus.logBBT': 'سجل حرارة الجسم',
    'focus.logMedication': 'سجل الدواء',
    'upcoming.title': 'اللي جاي',
    'upcoming.nextPeriod': 'الحيض الجاي المتوقع',
    'upcoming.inDays': 'ف',
    'upcoming.daysText': 'أيام',
    'upcoming.activeNow': 'نشط دابا',
    'upcoming.onTrack': 'مغادي مزيان',
    'upcoming.checkup': 'فحص العافية',
    'upcoming.scheduled': 'مجدول عبر منصة الفحص',
    'actions.edit': 'تعديل',
    'actions.viewAll': 'شوف الكل'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    // Automatically switch document text direction for Arabic & Darija
    const isRtl = language === 'ar' || language === 'darija';
    document.documentElement.setAttribute('dir', isRtl ? 'rtl' : 'ltr');
  }, [language]);

  const isRTL = language === 'ar' || language === 'darija';

  // Translation function `t(key, fallback)`
  const t = (key, fallback) => {
    const langDict = translations[language] || translations['en'];
    return langDict[key] || translations['en'][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}