import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Comprehensive dictionary keyed by standard short codes
const translations = {
  en: {
    'greeting.morning': 'Good morning',
    'greeting.afternoon': 'Good afternoon',
    'greeting.evening': 'Good evening',
    'dashboard.bodyInPhase': 'Your body is in the',
    'dashboard.protectedPhase': 'protected phase',
    'river.title': 'Signal River',
    'river.tooltip': "Your body's signals over the last 7 days",
    'river.patternNoticed': 'Pattern noticed',
    'river.subtitle': "Your body's signals over the last 7 days",
    'days.fatigue': 'Fatigue',
    'days.poorSleep': 'Poor sleep',
    'days.headache': 'Headache',
    'days.mildCramps': 'Mild cramps',
    'days.ovulationWindow': 'Ovulation window',
    'days.today': 'Today',
    'days.thu': 'Thu',
    'days.fri': 'Fri',
    'days.sat': 'Sat',
    'days.sun': 'Sun',
    'days.mon': 'Mon',
    'days.tue': 'Tue',
    'dates.may9': 'May 9',
    'dates.may10': 'May 10',
    'dates.may11': 'May 11',
    'dates.may12': 'May 12',
    'dates.may13': 'May 13',
    'dates.may14': 'May 14',
    'dates.may15': 'May 15',
    'river.recentFlow': 'Your recent signal flow:',
    'river.flowDescription': 'fatigue and poor sleep appeared together twice this week. Your flow is calmer today.',
    'river.disclaimer': 'This is a personalized interpretation, not a medical diagnosis.',
    'aura.badge': 'Aura AI · Supportive Sisterhood',
    'aura.encrypted': 'Encrypted',
    'aura.safeSpaceTitle': 'Your Safe Space Guidance',
    'aura.default': 'Prioritizing rest during high-stress weeks protects your hormonal rhythm. Take 5 deep breaths today.',
    'aura.menstrual': 'Your body is in its renewal phase. Warm hydration and gentle pacing will support your comfort today.',
    'aura.luteal': 'Progesterone is shifting inward. Give yourself permission to step back and protect your emotional space.',
    'aura.crampy': 'We noticed discomfort logged. Consider a gentle stretch or reaching out to a specialist if needed.',
    'focus.title': "Today's Focus",
    'focus.logSymptoms': 'Log symptoms',
    'focus.logMood': 'Log mood',
    'focus.logBBT': 'Log BBT',
    'focus.logMedication': 'Log medication',
    'upcoming.title': 'Upcoming',
    'upcoming.nextPeriod': 'Next Period Expected',
    'upcoming.inDays': 'In',
    'upcoming.daysText': 'days',
    'upcoming.activeNow': 'Active now',
    'upcoming.onTrack': 'On track',
    'upcoming.checkup': 'Wellness Checkup',
    'upcoming.scheduled': 'Scheduled via Screening Hub',
    'actions.edit': 'Edit',
    'actions.viewAll': 'View all',

    // --- Maternal & Screening Hub ---
    'hub.badge': 'High-Stakes Life Stage & Preventive Care',
    'hub.title': "Maternal & Women's Health Hub",
    'hub.subtitle': 'Structured clinical tracking built around WHO antenatal standards, intelligent symptom segmentation, and preventive health reminders.',

    'tabs.maternal_journey': '🤱 Maternal Journey',
    'tabs.screening_story': '🩺 Screening & Health Story',

    'journey.tab_dashboard': '1. Pregnancy Dashboard',
    'journey.tab_antenatal': '2. Antenatal Visits',
    'journey.tab_symptoms': '3. Symptom Tracker',
    'journey.tab_education': '4. Trimester Guide',

    'dashboard.current_progress': 'Current Progress',
    'dashboard.week_info': 'Week 24 • 2nd Trimester',
    'dashboard.baby_size': '👶 Baby size: Corn Ear (~30cm, 600g)',
    'dashboard.countdown': 'Next Antenatal Visit Countdown:',
    'dashboard.days_remaining': '5 days remaining',
    'dashboard.who_contact': 'WHO Contact #4 of 8',
    'dashboard.feeling_prompt': 'How are you feeling today?',
    'dashboard.feeling_placeholder': 'e.g. Mild back fatigue, good energy...',
    'dashboard.save_checkin': 'Save Check-in',
    'dashboard.checkin_saved': 'Quick check-in saved successfully!',

    'antenatal.schedule_title': 'WHO 8-Contact Schedule Checklist',
    'antenatal.schedule_desc': 'Track completed vs. upcoming clinical milestones to ensure optimal maternal health.',
    'antenatal.c1': 'Contact 1 (Up to 12 weeks)',
    'antenatal.c2': 'Contact 2 (20 weeks)',
    'antenatal.c3': 'Contact 3 (26 weeks)',
    'antenatal.c4': 'Contact 4 (30 weeks)',
    'antenatal.completed': 'Completed',
    'antenatal.upcoming': 'Upcoming',
    'antenatal.scheduled': 'Scheduled',
    'antenatal.ai_title': '✨ Pre-Visit AI Consultation Summary',
    'antenatal.ai_desc': 'Your logged symptoms and questions are auto-organized into a clear brief for your doctor.',
    'antenatal.ai_bullet1': '• Frequency of mild lower back pain increased over past 4 days.',
    'antenatal.ai_bullet2': '• Question for clinician: Safe stretching routines for third trimester?',

    'symptoms.urgent_title': 'Urgent Flags (Immediate Action Required)',
    'symptoms.urgent_desc': 'Severe headache, vision changes, sudden swelling, reduced fetal movement, bleeding, or fever. Never blended with routine logging.',
    'symptoms.call_emergency': '📞 Call Doctor / Emergency Now',
    'symptoms.routine_title': 'Routine Log',
    'symptoms.routine_desc': 'Nausea, fatigue, mild back pain, sleep quality — logged casually with no alarm styling.',
    'symptoms.routine_placeholder': 'Log daily routine symptoms...',
    'symptoms.save_routine': 'Save Routine Entry',

    'education.title': 'Trimester-by-Trimester Guides',
    'education.desc': 'Short, non-alarming explainers curated to help you understand what is normal and expected at each specific stage of your pregnancy journey.',
    'education.g1': 'First Trimester: Early development & managing fatigue',
    'education.g2': 'Second Trimester: Movement, nutrition, & body changes',
    'education.g3': 'Third Trimester: Preparation, birth signs, & postpartum planning',

    'screening.sub_reminders': '🩺 Preventive Reminders',
    'screening.sub_story': '📖 My Health Story',
    'screening.sub_conditions': '🛡️ Women’s Health Focus',
    'screening.disclaimer': 'These are general awareness reminders based on standard medical screening intervals—not a diagnosis or personalized medical recommendation. Consult your healthcare specialist about your specific health needs.',
    'screening.error_fetch': 'Failed to fetch screening reminders from backend.',
    'screening.error_date': 'Please select a valid date for {type}.',
    'screening.success_update': 'Successfully updated record for {type}!',
    'screening.error_update': 'Failed to update screening date.',
    'screening.loading': 'Loading schedule from server...',
    'screening.empty': 'No screening reminders found in your account profile.',
    'screening.due': 'Due',
    'screening.up_to_date': 'Up to date',
    'screening.last_logged': 'Last logged:',
    'screening.never': 'Never',
    'screening.log_completed': 'Log completed',
    'screening.save_date': 'Save date',
    'screening.saving': 'Saving…',

    'story.title': 'My Health Story',
    'story.share_summary': 'Share Summary',
    'story.range_1m': '1 Month',
    'story.range_3m': '3 Months',
    'story.range_6m': '6 Months',
    'story.summary_header': 'Summary for May 1 – May 14, 2024',
    'story.generated_on': 'Generated on May 14, 2024',
    'story.main_concerns': 'Main concerns',
    'story.concerns_text': 'Frequent lower back fatigue and intermittent sleep disruptions reported during the current period.',
    'story.key_insights': 'Key Insights',
    'story.insights_text': 'Consistent tracking helps flag patterns early. Consider discussing stretching techniques during your next scheduled clinical visit.',

    'conditions.title': 'Targeted Women’s Health Focus',
    'conditions.desc': 'Explore educational overviews and foundational awareness guides regarding key conditions affecting women’s wellness.',
    'conditions.c1_title': 'PCOS (Polycystic Ovary Syndrome)',
    'conditions.c1_desc': 'Understanding hormonal balance, cycle monitoring, and lifestyle management approaches.',
    'conditions.c2_title': 'Endometriosis Awareness',
    'conditions.c2_desc': 'Recognizing pelvic discomfort patterns and partnering effectively with specialists.',
    'conditions.c3_title': 'Bone Density & Calcium Health',
    'conditions.c3_desc': 'Long-term nutritional support and preventive strategies across different life stages.'
  },
  ar: {
    'greeting.morning': 'صباح الخير',
    'greeting.afternoon': 'مساء الخير',
    'greeting.evening': 'مساء الخير',
    'dashboard.bodyInPhase': 'جسمك في',
    'dashboard.protectedPhase': 'المرحلة المحمية',
    'river.title': 'نهر الإشارات',
    'river.tooltip': 'إشارات جسمك خلال الأيام الـ 7 الماضية',
    'river.patternNoticed': 'تم ملاحظة نمط',
    'river.subtitle': 'إشارات جسمك خلال الأيام الـ 7 الماضية',
    'days.fatigue': 'إرهاق',
    'days.poorSleep': 'نوم سيء',
    'days.headache': 'صداع',
    'days.mildCramps': 'تقلصات خفيفة',
    'days.ovulationWindow': 'فترة الإباضة',
    'days.today': 'اليوم',
    'days.thu': 'الخميس',
    'days.fri': 'الجمعة',
    'days.sat': 'السبت',
    'days.sun': 'الأحد',
    'days.mon': 'الإثنين',
    'days.tue': 'الثلاثاء',
    'dates.may9': '٩ مايو',
    'dates.may10': '١٠ مايو',
    'dates.may11': '١١ مايو',
    'dates.may12': '١٢ مايو',
    'dates.may13': '١٣ مايو',
    'dates.may14': '١٤ مايو',
    'dates.may15': '١٥ مايو',
    'river.recentFlow': 'تدفق إشاراتك الأخير:',
    'river.flowDescription': 'ظهر الإرهاق وسوء النوم معاً مرتين هذا الأسبوع. تدفقك أهدأ اليوم.',
    'river.disclaimer': 'هذه قراءة مخصصة وليست تشخيصاً طبياً.',
    'aura.badge': 'أورا الذكاء الاصطناعي · أخوة داعمة',
    'aura.encrypted': 'مشفر',
    'aura.safeSpaceTitle': 'إرشادات مساحتك الآمنة',
    'aura.default': 'إعطاء الأولوية للراحة خلال أسابيع الضغط العالي يحمي إيقاع هرموناتك. خذي ٥ أنفاس عميقة اليوم.',
    'aura.menstrual': 'جسمك في مرحلة التجديد. السوائل الدافئة والوتيرة الهادئة ستدعم راحتك اليوم.',
    'aura.luteal': 'البروجسترون يتجه للداخل. امنحي نفسك الإذن بالتراجع وحماية مساحتك العاطفية.',
    'aura.crampy': 'لاحظنا تسجيل شعور عدم راحة. فكري في تمارين إطالة خفيفة أو التواصل مع مختص إذا لزم الأمر.',
    'focus.title': 'تركيز اليوم',
    'focus.logSymptoms': 'تسجيل الأعراض',
    'focus.logMood': 'تسجيل المزاج',
    'focus.logBBT': 'تسجيل حرارة الجسم',
    'focus.logMedication': 'تسجيل الأدوية',
    'upcoming.title': 'القادم',
    'upcoming.nextPeriod': 'الدورة القادمة المتوقعة',
    'upcoming.inDays': 'خلال',
    'upcoming.daysText': 'أيام',
    'upcoming.activeNow': 'نشطة الآن',
    'upcoming.onTrack': 'على المسار',
    'upcoming.checkup': 'فحص العافية',
    'upcoming.scheduled': 'مجدول عبر مركز الفحص',
    'actions.edit': 'تعديل',
    'actions.viewAll': 'عرض الكل',

    // --- Maternal & Screening Hub ---
    'hub.badge': 'مرحلة حياتية بالغة الأهمية ورعاية وقائية',
    'hub.title': 'مركز صحة الأمومة والمرأة',
    'hub.subtitle': 'متابعة سريرية منظمة مبنية على معايير الرعاية السابقة للولادة الخاصة بمنظمة الصحة العالمية، مع تصنيف ذكي للأعراض وتذكيرات صحية وقائية.',

    'tabs.maternal_journey': '🤱 رحلة الأمومة',
    'tabs.screening_story': '🩺 الفحوصات وقصتي الصحية',

    'journey.tab_dashboard': '1. لوحة الحمل',
    'journey.tab_antenatal': '2. زيارات ما قبل الولادة',
    'journey.tab_symptoms': '3. متابعة الأعراض',
    'journey.tab_education': '4. دليل الأثلوث',

    'dashboard.current_progress': 'التقدم الحالي',
    'dashboard.week_info': 'الأسبوع 24 • الثلث الثاني',
    'dashboard.baby_size': '👶 حجم الطفل: كوز ذرة (~30 سم، 600 غرام)',
    'dashboard.countdown': 'العد التنازلي لزيارة ما قبل الولادة القادمة:',
    'dashboard.days_remaining': 'باقي 5 أيام',
    'dashboard.who_contact': 'زيارة منظمة الصحة العالمية رقم 4 من 8',
    'dashboard.feeling_prompt': 'كيف تشعرين اليوم؟',
    'dashboard.feeling_placeholder': 'مثال: تعب خفيف في الظهر، طاقة جيدة...',
    'dashboard.save_checkin': 'حفظ المتابعة',
    'dashboard.checkin_saved': 'تم حفظ المتابعة السريعة بنجاح!',

    'antenatal.schedule_title': 'قائمة الزيارات الثمانية لمنظمة الصحة العالمية',
    'antenatal.schedule_desc': 'تابعي المحطات السريرية المكتملة والقادمة لضمان صحة مثالية للأم.',
    'antenatal.c1': 'الزيارة 1 (حتى 12 أسبوعاً)',
    'antenatal.c2': 'الزيارة 2 (20 أسبوعاً)',
    'antenatal.c3': 'الزيارة 3 (26 أسبوعاً)',
    'antenatal.c4': 'الزيارة 4 (30 أسبوعاً)',
    'antenatal.completed': 'مكتملة',
    'antenatal.upcoming': 'قادمة',
    'antenatal.scheduled': 'مجدولة',
    'antenatal.ai_title': '✨ ملخص الذكاء الاصطناعي قبل الزيارة',
    'antenatal.ai_desc': 'يتم تنظيم الأعراض والأسئلة المسجلة تلقائياً في ملخص واضح لطبيبك.',
    'antenatal.ai_bullet1': '• زاد تكرار ألم أسفل الظهر الخفيف خلال الأيام الأربعة الماضية.',
    'antenatal.ai_bullet2': '• سؤال للطبيب: ما هي تمارين الإطالة الآمنة للثلث الثالث؟',

    'symptoms.urgent_title': 'إشارات عاجلة (تتطلب إجراءً فورياً)',
    'symptoms.urgent_desc': 'صداع شديد، تغيرات في الرؤية، تورم مفاجئ، انخفاض حركة الجنين، نزيف، أو حمى. لا تُمزج أبداً مع التسجيل الروتيني.',
    'symptoms.call_emergency': '📞 اتصلي بالطبيب / الطوارئ الآن',
    'symptoms.routine_title': 'السجل الروتيني',
    'symptoms.routine_desc': 'غثيان، تعب، ألم خفيف في الظهر، جودة النوم — تُسجَّل بشكل عادي دون أي طابع تنبيهي.',
    'symptoms.routine_placeholder': 'سجلي الأعراض الروتينية اليومية...',
    'symptoms.save_routine': 'حفظ السجل الروتيني',

    'education.title': 'أدلة كل ثلث من الحمل',
    'education.desc': 'شروحات قصيرة وغير مثيرة للقلق لمساعدتك على فهم ما هو طبيعي ومتوقع في كل مرحلة من رحلة حملك.',
    'education.g1': 'الثلث الأول: النمو المبكر وإدارة التعب',
    'education.g2': 'الثلث الثاني: الحركة، التغذية، وتغيرات الجسم',
    'education.g3': 'الثلث الثالث: التحضير، علامات الولادة، وتخطيط ما بعد الولادة',

    'screening.sub_reminders': '🩺 تذكيرات وقائية',
    'screening.sub_story': '📖 قصتي الصحية',
    'screening.sub_conditions': '🛡️ التركيز على صحة المرأة',
    'screening.disclaimer': 'هذه تذكيرات توعوية عامة مبنية على فترات الفحص الطبي المعتادة — وليست تشخيصاً أو توصية طبية شخصية. استشيري أخصائي الرعاية الصحية بخصوص احتياجاتك الصحية الخاصة.',
    'screening.error_fetch': 'فشل في جلب تذكيرات الفحص من الخادم.',
    'screening.error_date': 'يرجى اختيار تاريخ صالح لـ {type}.',
    'screening.success_update': 'تم تحديث سجل {type} بنجاح!',
    'screening.error_update': 'فشل تحديث تاريخ الفحص.',
    'screening.loading': 'جارٍ تحميل الجدول من الخادم...',
    'screening.empty': 'لم يتم العثور على تذكيرات فحص في ملفك الشخصي.',
    'screening.due': 'مستحق',
    'screening.up_to_date': 'محدّث',
    'screening.last_logged': 'آخر تسجيل:',
    'screening.never': 'أبداً',
    'screening.log_completed': 'تسجيل إتمام',
    'screening.save_date': 'حفظ التاريخ',
    'screening.saving': 'جارٍ الحفظ…',

    'story.title': 'قصتي الصحية',
    'story.share_summary': 'مشاركة الملخص',
    'story.range_1m': 'شهر واحد',
    'story.range_3m': '3 أشهر',
    'story.range_6m': '6 أشهر',
    'story.summary_header': 'ملخص من 1 إلى 14 مايو 2024',
    'story.generated_on': 'تم الإنشاء في 14 مايو 2024',
    'story.main_concerns': 'أبرز المخاوف',
    'story.concerns_text': 'تم الإبلاغ عن تعب متكرر أسفل الظهر واضطرابات نوم متقطعة خلال الفترة الحالية.',
    'story.key_insights': 'أبرز الملاحظات',
    'story.insights_text': 'المتابعة المستمرة تساعد على ملاحظة الأنماط مبكراً. فكري في مناقشة تقنيات الإطالة في زيارتك السريرية القادمة.',

    'conditions.title': 'تركيز موجه على صحة المرأة',
    'conditions.desc': 'استكشفي نظرات تعليمية عامة وأدلة توعوية أساسية حول الحالات الرئيسية التي تؤثر على صحة المرأة.',
    'conditions.c1_title': 'متلازمة تكيس المبايض',
    'conditions.c1_desc': 'فهم التوازن الهرموني، متابعة الدورة، وأساليب إدارة نمط الحياة.',
    'conditions.c2_title': 'التوعية بالانتباذ البطاني الرحمي',
    'conditions.c2_desc': 'التعرف على أنماط الانزعاج الحوضي والتعاون بفعالية مع المختصين.',
    'conditions.c3_title': 'كثافة العظام وصحة الكالسيوم',
    'conditions.c3_desc': 'الدعم الغذائي طويل الأمد واستراتيجيات وقائية عبر مختلف مراحل الحياة.'
  },
  fr: {
    'greeting.morning': 'Bonjour',
    'greeting.afternoon': 'Bon après-midi',
    'greeting.evening': 'Bonsoir',
    'dashboard.bodyInPhase': 'Votre corps est dans la',
    'dashboard.protectedPhase': 'phase protégée',
    'river.title': 'Rivière des Signaux',
    'river.tooltip': 'Les signaux de votre corps au cours des 7 derniers jours',
    'river.patternNoticed': 'Modèle détecté',
    'river.subtitle': 'Les signaux de votre corps au cours des 7 derniers jours',
    'days.fatigue': 'Fatigue',
    'days.poorSleep': 'Sommeil agité',
    'days.headache': 'Maux de tête',
    'days.mildCramps': 'Légères crampes',
    'days.ovulationWindow': "Fenêtre d'ovulation",
    'days.today': "Aujourd'hui",
    'days.thu': 'Jeu',
    'days.fri': 'Ven',
    'days.sat': 'Sam',
    'days.sun': 'Dim',
    'days.mon': 'Lun',
    'days.tue': 'Mar',
    'dates.may9': '9 mai',
    'dates.may10': '10 mai',
    'dates.may11': '11 mai',
    'dates.may12': '12 mai',
    'dates.may13': '13 mai',
    'dates.may14': '14 mai',
    'dates.may15': '15 mai',
    'river.recentFlow': 'Votre flux de signaux récent :',
    'river.flowDescription': 'la fatigue et le mauvais sommeil sont apparus ensemble deux fois cette semaine. Votre flux est plus calme aujourd’hui.',
    'river.disclaimer': "Ceci est une interprétation personnalisée, pas un diagnostic médical.",
    'aura.badge': 'Aura IA · Sororité de soutien',
    'aura.encrypted': 'Crypté',
    'aura.safeSpaceTitle': 'Conseils pour votre espace sécurisé',
    'aura.default': 'Prioriser le repos pendant les semaines de stress intense protège votre rythme hormonal. Prenez 5 respirations profondes aujourd’hui.',
    'aura.menstrual': 'Votre corps est en phase de renouvellement. Une hydratation chaude et un rythme doux soutiendront votre confort.',
    'aura.luteal': 'La progestérone évolue vers l’intérieur. Donnez-vous la permission de prendre du recul et de protéger votre espace émotionnel.',
    'aura.crampy': 'Nous avons détecté un signal d’inconfort. Envisagez des étirements doux ou consultez un spécialiste si nécessaire.',
    'focus.title': "Focus d'aujourd'hui",
    'focus.logSymptoms': 'Enregistrer les symptômes',
    'focus.logMood': "Enregistrer l'humeur",
    'focus.logBBT': 'Enregistrer la température',
    'focus.logMedication': 'Enregistrer les médicaments',
    'upcoming.title': 'À venir',
    'upcoming.nextPeriod': 'Prochaines règles prévues',
    'upcoming.inDays': 'Dans',
    'upcoming.daysText': 'jours',
    'upcoming.activeNow': 'Actif maintenant',
    'upcoming.onTrack': 'Sur la bonne voie',
    'upcoming.checkup': 'Bilan de santé',
    'upcoming.scheduled': 'Programmé via le centre de dépistage',
    'actions.edit': 'Modifier',
    'actions.viewAll': 'Voir tout',

    // --- Maternal & Screening Hub ---
    'hub.badge': 'Étape de vie décisive & soins préventifs',
    'hub.title': 'Espace Santé Maternelle & Féminine',
    'hub.subtitle': 'Suivi clinique structuré basé sur les normes prénatales de l’OMS, une segmentation intelligente des symptômes et des rappels de santé préventifs.',

    'tabs.maternal_journey': '🤱 Parcours maternel',
    'tabs.screening_story': '🩺 Dépistage & Historique de santé',

    'journey.tab_dashboard': '1. Tableau de bord de grossesse',
    'journey.tab_antenatal': '2. Visites prénatales',
    'journey.tab_symptoms': '3. Suivi des symptômes',
    'journey.tab_education': '4. Guide des trimestres',

    'dashboard.current_progress': 'Progression actuelle',
    'dashboard.week_info': 'Semaine 24 • 2ème trimestre',
    'dashboard.baby_size': '👶 Taille du bébé : épi de maïs (~30 cm, 600 g)',
    'dashboard.countdown': 'Compte à rebours avant la prochaine visite prénatale :',
    'dashboard.days_remaining': '5 jours restants',
    'dashboard.who_contact': 'Contact OMS n°4 sur 8',
    'dashboard.feeling_prompt': 'Comment vous sentez-vous aujourd’hui ?',
    'dashboard.feeling_placeholder': 'ex. légère fatigue dans le dos, bonne énergie...',
    'dashboard.save_checkin': 'Enregistrer le bilan',
    'dashboard.checkin_saved': 'Bilan rapide enregistré avec succès !',

    'antenatal.schedule_title': 'Liste des 8 contacts recommandés par l’OMS',
    'antenatal.schedule_desc': 'Suivez les étapes cliniques accomplies et à venir pour une santé maternelle optimale.',
    'antenatal.c1': 'Contact 1 (jusqu’à 12 semaines)',
    'antenatal.c2': 'Contact 2 (20 semaines)',
    'antenatal.c3': 'Contact 3 (26 semaines)',
    'antenatal.c4': 'Contact 4 (30 semaines)',
    'antenatal.completed': 'Terminé',
    'antenatal.upcoming': 'À venir',
    'antenatal.scheduled': 'Programmé',
    'antenatal.ai_title': '✨ Résumé IA avant la visite',
    'antenatal.ai_desc': 'Vos symptômes et questions enregistrés sont automatiquement organisés en un résumé clair pour votre médecin.',
    'antenatal.ai_bullet1': '• Fréquence accrue de douleurs légères au bas du dos ces 4 derniers jours.',
    'antenatal.ai_bullet2': '• Question pour le médecin : quels étirements sont sûrs au troisième trimestre ?',

    'symptoms.urgent_title': 'Signaux urgents (action immédiate requise)',
    'symptoms.urgent_desc': 'Maux de tête sévères, troubles de la vision, gonflement soudain, mouvements fœtaux réduits, saignements ou fièvre. Jamais mélangé avec le suivi de routine.',
    'symptoms.call_emergency': '📞 Appeler le médecin / les urgences maintenant',
    'symptoms.routine_title': 'Journal de routine',
    'symptoms.routine_desc': 'Nausées, fatigue, légères douleurs dorsales, qualité du sommeil — enregistrés simplement, sans mise en forme alarmante.',
    'symptoms.routine_placeholder': 'Enregistrez vos symptômes quotidiens...',
    'symptoms.save_routine': 'Enregistrer l’entrée de routine',

    'education.title': 'Guides trimestre par trimestre',
    'education.desc': 'Des explications courtes et rassurantes pour comprendre ce qui est normal et attendu à chaque étape de votre grossesse.',
    'education.g1': 'Premier trimestre : développement précoce et gestion de la fatigue',
    'education.g2': 'Deuxième trimestre : mouvement, nutrition et changements corporels',
    'education.g3': 'Troisième trimestre : préparation, signes de l’accouchement et planification post-partum',

    'screening.sub_reminders': '🩺 Rappels préventifs',
    'screening.sub_story': '📖 Mon historique de santé',
    'screening.sub_conditions': '🛡️ Focus santé féminine',
    'screening.disclaimer': 'Il s’agit de rappels de sensibilisation généraux basés sur les intervalles de dépistage médical standards — pas un diagnostic ni une recommandation médicale personnalisée. Consultez votre professionnel de santé pour vos besoins spécifiques.',
    'screening.error_fetch': 'Échec de la récupération des rappels de dépistage depuis le serveur.',
    'screening.error_date': 'Veuillez sélectionner une date valide pour {type}.',
    'screening.success_update': 'Le dossier de {type} a été mis à jour avec succès !',
    'screening.error_update': 'Échec de la mise à jour de la date de dépistage.',
    'screening.loading': 'Chargement du calendrier depuis le serveur...',
    'screening.empty': 'Aucun rappel de dépistage trouvé dans votre profil.',
    'screening.due': 'À faire',
    'screening.up_to_date': 'À jour',
    'screening.last_logged': 'Dernier enregistrement :',
    'screening.never': 'Jamais',
    'screening.log_completed': 'Enregistrer comme fait',
    'screening.save_date': 'Enregistrer la date',
    'screening.saving': 'Enregistrement…',

    'story.title': 'Mon historique de santé',
    'story.share_summary': 'Partager le résumé',
    'story.range_1m': '1 mois',
    'story.range_3m': '3 mois',
    'story.range_6m': '6 mois',
    'story.summary_header': 'Résumé du 1er au 14 mai 2024',
    'story.generated_on': 'Généré le 14 mai 2024',
    'story.main_concerns': 'Principales préoccupations',
    'story.concerns_text': 'Fatigue fréquente du bas du dos et perturbations intermittentes du sommeil signalées durant la période actuelle.',
    'story.key_insights': 'Points clés',
    'story.insights_text': 'Un suivi régulier aide à repérer les tendances tôt. Pensez à aborder les techniques d’étirement lors de votre prochaine visite clinique.',

    'conditions.title': 'Focus ciblé sur la santé féminine',
    'conditions.desc': 'Découvrez des aperçus éducatifs et des guides de sensibilisation sur les principales conditions affectant le bien-être des femmes.',
    'conditions.c1_title': 'SOPK (Syndrome des ovaires polykystiques)',
    'conditions.c1_desc': 'Comprendre l’équilibre hormonal, le suivi du cycle et les approches de gestion du mode de vie.',
    'conditions.c2_title': 'Sensibilisation à l’endométriose',
    'conditions.c2_desc': 'Reconnaître les schémas d’inconfort pelvien et collaborer efficacement avec des spécialistes.',
    'conditions.c3_title': 'Densité osseuse et santé du calcium',
    'conditions.c3_desc': 'Soutien nutritionnel à long terme et stratégies préventives selon les différentes étapes de la vie.'
  },
  darija: {
    'greeting.morning': 'صباح الخير',
    'greeting.afternoon': 'مساء الخير',
    'greeting.evening': 'مساء الخير',
    'dashboard.bodyInPhase': 'الجسم ديالك فالمرحلة',
    'dashboard.protectedPhase': 'المحمية',
    'river.title': 'وادي الإشارات',
    'river.tooltip': 'الإشارات ديال جسمك فالـ 7 أيام الأخيرة',
    'river.patternNoticed': 'تم ملاحظة نمط',
    'river.subtitle': 'الإشارات ديال جسمك فالـ 7 أيام الأخيرة',
    'days.fatigue': 'عياء',
    'days.poorSleep': 'نعاس ماشي هو هداك',
    'days.headache': 'وجع الرأس',
    'days.mildCramps': 'حريق خفيف',
    'days.ovulationWindow': 'فترة الإباضة',
    'days.today': 'اليوم',
    'days.thu': 'الخميس',
    'days.fri': 'الجمعة',
    'days.sat': 'السبت',
    'days.sun': 'الأحد',
    'days.mon': 'الإثنين',
    'days.tue': 'الثلاثاء',
    'dates.may9': '9 ماي',
    'dates.may10': '10 ماي',
    'dates.may11': '11 ماي',
    'dates.may12': '12 ماي',
    'dates.may13': '13 ماي',
    'dates.may14': '14 ماي',
    'dates.may15': '15 ماي',
    'river.recentFlow': 'التدفق الأخير ديال إشاراتك:',
    'river.flowDescription': 'العياء وقلة النعاس بانوا بجوج جوج مرات هاد السيمانة. التدفق هادئ اليوم.',
    'river.disclaimer': 'هادشي تفسير شخصي ماشي تشخيص طبي.',
    'aura.badge': 'أورا الذكاء الاصطناعي · مساندة النساء',
    'aura.encrypted': 'مشفر',
    'aura.safeSpaceTitle': 'إرشادات المساحة الآمنة ديالك',
    'aura.default': 'الراحة فالأسام ديال الستريس كتحمي الهرمونات ديالك. تنفسي بعمق 5 المرات اليوم.',
    'aura.menstrual': 'الجسم ديالك كيدوز من مرحلة التجديد. السوائل السخونة والراحة غادي يعاونوك اليوم.',
    'aura.luteal': 'البروجسترون كيتغير لداخل. عطي لراسك الوقت باش ترتاحي وتحمي المساحة العاطفية ديالك.',
    'aura.crampy': 'لاحظنا بلي تسجل عندك حريق. فكري ديري تمدد خفيف ولا تواصلي مع مختص يلا كان ضروري.',
    'focus.title': 'تركيز اليوم',
    'focus.logSymptoms': 'سجل الأعراض',
    'focus.logMood': 'سجل الحالة النفسية',
    'focus.logBBT': 'سجل حرارة الجسم',
    'focus.logMedication': 'سجل الدواء',
    'upcoming.title': 'اللي جاي',
    'upcoming.nextPeriod': 'الحيض الجاي المتوقع',
    'upcoming.inDays': 'ف',
    'upcoming.daysText': 'أيام',
    'upcoming.activeNow': 'نشط دابا',
    'upcoming.onTrack': 'مغادي مزيان',
    'upcoming.checkup': 'فحص العافية',
    'upcoming.scheduled': 'مجدول عبر منصة الفحص',
    'actions.edit': 'تعديل',
    'actions.viewAll': 'شوف الكل',

    // --- Maternal & Screening Hub ---
    'hub.badge': 'مرحلة مهمة فحياتك ورعاية وقائية',
    'hub.title': 'مركز صحة الأمومة والمرأة',
    'hub.subtitle': 'متابعة سريرية منظمة بناءً على معايير منظمة الصحة العالمية ديال قبل الولادة، مع تصنيف ذكي للأعراض وتذكيرات صحية وقائية.',

    'tabs.maternal_journey': '🤱 مسار الأمومة',
    'tabs.screening_story': '🩺 الفحوصات وقصتي الصحية',

    'journey.tab_dashboard': '1. لوحة الحمل',
    'journey.tab_antenatal': '2. الزيارات ديال قبل الولادة',
    'journey.tab_symptoms': '3. متابعة الأعراض',
    'journey.tab_education': '4. دليل الأثلاث',

    'dashboard.current_progress': 'التقدم الحالي',
    'dashboard.week_info': 'الأسبوع 24 • الثلث الثاني',
    'dashboard.baby_size': '👶 حجم البيبي: كوز الذرة (~30 سم، 600 غ)',
    'dashboard.countdown': 'العد التنازلي للزيارة الجاية ديال قبل الولادة:',
    'dashboard.days_remaining': 'باقي 5 ديال الأيام',
    'dashboard.who_contact': 'الزيارة رقم 4 من 8 ديال منظمة الصحة العالمية',
    'dashboard.feeling_prompt': 'كيف حاسة اليوم؟',
    'dashboard.feeling_placeholder': 'مثلاً: عياء خفيف فالضهر، طاقة مزيانة...',
    'dashboard.save_checkin': 'حفظ المتابعة',
    'dashboard.checkin_saved': 'تسجلات المتابعة السريعة بنجاح!',

    'antenatal.schedule_title': 'لائحة الزيارات الثمانية ديال منظمة الصحة العالمية',
    'antenatal.schedule_desc': 'تابعي المحطات السريرية اللي كملات واللي جايين باش تضمني صحة مزيانة للأم.',
    'antenatal.c1': 'الزيارة 1 (حتى 12 سيمانة)',
    'antenatal.c2': 'الزيارة 2 (20 سيمانة)',
    'antenatal.c3': 'الزيارة 3 (26 سيمانة)',
    'antenatal.c4': 'الزيارة 4 (30 سيمانة)',
    'antenatal.completed': 'كملات',
    'antenatal.upcoming': 'جاية',
    'antenatal.scheduled': 'مجدولة',
    'antenatal.ai_title': '✨ ملخص الذكاء الاصطناعي قبل الزيارة',
    'antenatal.ai_desc': 'الأعراض والأسئلة اللي سجلتي كيتنظمو أوتوماتيكياً فملخص واضح للطبيب ديالك.',
    'antenatal.ai_bullet1': '• زاد تكرار وجع خفيف فأسفل الضهر فالـ4 أيام الأخيرة.',
    'antenatal.ai_bullet2': '• سؤال للطبيب: شنو هي تمارين التمدد الآمنة فالثلث الثالث؟',

    'symptoms.urgent_title': 'إشارات مستعجلة (كتطلب تدخل فوري)',
    'symptoms.urgent_desc': 'صداع قوي، تغيرات فالرؤية، تورم مفاجئ، نقصان حركة الجنين، نزيف، ولا حمى. عمرها ما كتخلط مع التسجيل العادي.',
    'symptoms.call_emergency': '📞 عيطي للطبيب / الطوارئ دابا',
    'symptoms.routine_title': 'السجل العادي',
    'symptoms.routine_desc': 'غثيان، عياء، وجع خفيف فالضهر، جودة النوم — كتسجل بطريقة عادية بلا أي طابع تنبيهي.',
    'symptoms.routine_placeholder': 'سجلي الأعراض العادية ديال كل نهار...',
    'symptoms.save_routine': 'حفظ السجل العادي',

    'education.title': 'أدلة كل ثلث ديال الحمل',
    'education.desc': 'شرح قصير وهادئ باش تفهمي شنو هو طبيعي ومتوقع فكل مرحلة ديال رحلة الحمل ديالك.',
    'education.g1': 'الثلث الأول: النمو المبكر وتدبير العياء',
    'education.g2': 'الثلث الثاني: الحركة، التغذية، وتغيرات الجسم',
    'education.g3': 'الثلث الثالث: التحضير، علامات الولادة، والتخطيط لما بعد الولادة',

    'screening.sub_reminders': '🩺 تذكيرات وقائية',
    'screening.sub_story': '📖 قصتي الصحية',
    'screening.sub_conditions': '🛡️ التركيز على صحة المرأة',
    'screening.disclaimer': 'هادو تذكيرات توعوية عامة مبنية على فترات الفحص الطبي العادية — ماشي تشخيص ولا توصية طبية شخصية. استشيري المختص ديال الصحة على حسب احتياجاتك.',
    'screening.error_fetch': 'ما قدرناش نجيبو تذكيرات الفحص من السيرفر.',
    'screening.error_date': 'خصك تختاري تاريخ صحيح ديال {type}.',
    'screening.success_update': 'تسجل السجل ديال {type} بنجاح!',
    'screening.error_update': 'ما قدرناش نحدثو تاريخ الفحص.',
    'screening.loading': 'كيتحمل الجدول من السيرفر...',
    'screening.empty': 'ما لقيناش أي تذكير فحص فالبروفيل ديالك.',
    'screening.due': 'خاصو',
    'screening.up_to_date': 'محدّث',
    'screening.last_logged': 'آخر تسجيل:',
    'screening.never': 'عمرها ما تسجلات',
    'screening.log_completed': 'سجلي كملات',
    'screening.save_date': 'حفظ التاريخ',
    'screening.saving': 'كيتسجل…',

    'story.title': 'قصتي الصحية',
    'story.share_summary': 'شارك الملخص',
    'story.range_1m': 'شهر واحد',
    'story.range_3m': '3 دشهور',
    'story.range_6m': '6 دشهور',
    'story.summary_header': 'ملخص من 1 حتى 14 ماي 2024',
    'story.generated_on': 'تصاوب ف14 ماي 2024',
    'story.main_concerns': 'الهموم الأساسية',
    'story.concerns_text': 'تسجل عياء متكرر فأسفل الضهر واضطرابات فالنوم من حين لآخر خلال هاد الفترة.',
    'story.key_insights': 'الملاحظات المهمة',
    'story.insights_text': 'المتابعة المستمرة كتعاون تلقاي الأنماط بكري. فكري تهضري على تقنيات التمدد فالزيارة السريرية الجاية.',

    'conditions.title': 'تركيز موجه لصحة المرأة',
    'conditions.desc': 'اكتشفي نظرات تعليمية عامة وأدلة توعوية أساسية على الحالات المهمة اللي كتأثر على صحة المرأة.',
    'conditions.c1_title': 'متلازمة تكيس المبايض',
    'conditions.c1_desc': 'فهم التوازن الهرموني، متابعة الدورة، وطرق تدبير نمط الحياة.',
    'conditions.c2_title': 'التوعية بانتباذ بطانة الرحم',
    'conditions.c2_desc': 'تعرفي على أنماط الانزعاج فالحوض وتعاوني مزيان مع المختصين.',
    'conditions.c3_title': 'كثافة العظام وصحة الكالسيوم',
    'conditions.c3_desc': 'دعم غذائي على المدى الطويل واستراتيجيات وقائية عبر مختلف مراحل الحياة.'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    // Automatically switch document text direction for Arabic & Darija
    const isRtl = language === 'ar' || language === 'darija';
    document.documentElement.setAttribute('dir', isRtl ? 'rtl' : 'ltr');
  }, [language]);

  const isRTL = language === 'ar' || language === 'darija';

  // Translation function `t(key, fallback, vars)`
  // `vars` is an optional object for simple {placeholder} interpolation,
  // e.g. t('screening.error_date', `...${type}`, { type }) -> "...Pap Smear"
  const t = (key, fallback, vars) => {
    const langDict = translations[language] || translations['en'];
    let str = langDict[key] || translations['en'][key] || fallback || key;
    if (vars) {
      Object.keys(vars).forEach((k) => {
        str = str.replace(new RegExp(`{${k}}`, 'g'), vars[k]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}